### PR TITLE
Make /UTF-8 flag on windows a separate config

### PR DESCRIPTION
**Pull request by knopp**
Hi, 

thank you for your work on this. We've been using heavily customized build from Chromium, but over time got stale so I was more than happy to replace it with your fork.

One of our dependency unfortunately uses Windows-1252 for header files encoding and forcing /UTF-8 makes MSVC complain about it.

It would be great if this was a separate config so that we can remove it where necessary.

### CODE REVIEW

**Comment by timniederhausen** [comment]
Thanks for doing that!
I'd move the comment to BUILDCONFIG though.

**Comment by knopp** [comment]
I can move the comment, but all other flags are explained directly in config/win/BUILD.gn. Wouldn't  this be inconsistent with the rest?

**Comment by timniederhausen** [comment]
In this case the comment explains why we set the flag by default.
Since the flag now has its own config, we should move that comment to where the config gets used.

**Comment by knopp** [comment]
I just got back to this. I can see you already merged the pull request.

**Comment by timniederhausen** [comment]
> 
> 
> I just got back to this. I can see you already merged the pull request.

yeah, I made some changes & committed it to master.
Still, thanks for your contribution!

**Pull request closed without merging**
